# Netlify Configuration File

# Settings for deploying to Netlify
[build]
  base = "frontend/"
  publish = "build/"
  command = "npm install && npm run build"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  REACT_APP_API_URL = "https://budget-travel-backend.onrender.com/api/v1"
