services:
  - name: backend
    type: web
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: BOOKING_AFFILIATE_ID
        value: demo-affiliate-id
      - key: BOOKING_API_KEY
        value: demo-api-key
